name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch: # Permite disparar manualmente

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permissão necessária para escrever arquivos no repositório

    steps:
      - uses: actions/checkout@v4 # Clona o repositório para que as ações possam acessá-lo

      # === seção para o lowlighter/metrics ===
      - name: Generate metrics (linguagens e estatísticas)
        uses: lowlighter/metrics@latest # Esta é a ação "tudo em um"
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Essencial para acessar seus dados do GitHub
          user: EduardoSBarbosa # Seu nome de usuário do GitHub
          template: classic # Estilo do gráfico. Outras opções: flat, terminal, etc.
          base: header, activity, community, repositories, metadata # Quais informações base incluir
          plugin_languages: yes # Habilita o plugin para mostrar as linguagens
          plugin_languages_ignored: javascript, html # Opcional: Linguagens para ignorar (ajuste se não quiser ver alguma)
          plugin_languages_threshold: 0% # Inclui linguagens com qualquer porcentagem de uso
          output_path: dist/github-metrics.svg # O caminho onde o SVG será salvo. Colocamos em 'dist/' diretamente.

      # Snake Animation 
      - name: Generate Snake Animation
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: EduardoSBarbosa
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Publica os resultados na branch 'output' (ou outra que você use para GH Pages)
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output # A branch para onde os arquivos SVG serão enviados
          build_dir: dist # O diretório de onde os arquivos serão publicados
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
